// <auto-generated />
using CPRG214.Assets.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CPRG214.Assets.Data.Migrations
{
    [DbContext(typeof(AssetsContext))]
    [Migration("20190329022958_InitialSeed")]
    partial class InitialSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CPRG214.Assets.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssetTypeId");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Manufacturer")
                        .IsRequired();

                    b.Property<string>("Model");

                    b.Property<string>("SerialNumber")
                        .IsRequired();

                    b.Property<string>("TagNumber")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetTypeId = 1,
                            Description = "Out of Stock",
                            Manufacturer = "Dell",
                            SerialNumber = "xbi-2938-1029",
                            TagNumber = "A100"
                        },
                        new
                        {
                            Id = 2,
                            AssetTypeId = 2,
                            Description = "On Sale",
                            Manufacturer = "LG",
                            Model = "UltraSharp",
                            SerialNumber = "nlw-8439-4839",
                            TagNumber = "A101"
                        },
                        new
                        {
                            Id = 3,
                            AssetTypeId = 2,
                            Description = "On Sale",
                            Manufacturer = "Acer",
                            Model = "V256HQL",
                            SerialNumber = "ixn-4938-2785",
                            TagNumber = "A103"
                        },
                        new
                        {
                            Id = 4,
                            AssetTypeId = 1,
                            Description = "Shipped",
                            Manufacturer = "Acer",
                            Model = "Aspire E 17",
                            SerialNumber = "bnx-4823-9857",
                            TagNumber = "A132"
                        },
                        new
                        {
                            Id = 5,
                            AssetTypeId = 3,
                            Description = "Refurbished",
                            Manufacturer = "Cisco",
                            Model = "CP-7841-K9",
                            SerialNumber = "osn-3928-9201",
                            TagNumber = "A423"
                        },
                        new
                        {
                            Id = 6,
                            AssetTypeId = 1,
                            Description = "Order Paid",
                            Manufacturer = "HP",
                            Model = "Pavillion",
                            SerialNumber = "aie-1235-4987",
                            TagNumber = "A435"
                        });
                });

            modelBuilder.Entity("CPRG214.Assets.Domain.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("AssetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phone"
                        });
                });

            modelBuilder.Entity("CPRG214.Assets.Domain.Asset", b =>
                {
                    b.HasOne("CPRG214.Assets.Domain.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
